import { Player } from "./player-model";

const PLACEHOLDER_IMAGE = "/Bollteori-transparent.png";

export const players: Player[] = [
  {
    name: "Andreas Svanström",
    image: "/Adde.jpg",
    position: "Försvarare",
    description:
      "Den här killen ville vinna troféer så då anslöt han sig till Bollteori för att ta hem den största troféen av alla, Korpen Trofén",
    goals: "11",
    assists: "16",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "1",
  },
  {
    name: "Oscar Ponce Johansson",
    image: "/Oscar_ponce.jpg",
    position: "Mittfältare",
    description: "Herr Krabba",
    goals: "4",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Robin Jakobsson",
    image: "/Robin_jakobsson.jpg",
    position: "Försvarare",
    description:
      "En Stenhård back som gjorde sin bästa match i livet när han var målvakt. Åkt på stryk av Paulo.",
    goals: "1",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Filip Rolf-Olsson",
    image: PLACEHOLDER_IMAGE,
    position: "Mittfältare",
    description: "Mer känd som Mr. Monke… ~150 cm",
    goals: "4",
    assists: "2",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "1",
  },
  {
    name: "Tom Alexandersson",
    image: "/Tom.jpg.jpg",
    position: "Försvarare",
    description: 'Definitionen av en "föredetting" Numera en kona i backlinjen...',
    goals: "0",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Erik Olsson Lidman",
    image: "/Erik_lidman.jpg",
    position: "Försvarare",
    description:
      "Snabba brillor och trädgårdshandskar i 20 grader plus är Erkans signatur.",
    goals: "0",
    assists: "1",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Jesper Berntsson",
    image: PLACEHOLDER_IMAGE,
    position: "Målvakt",
    description: "Fjärdemålis och maskot med ansvar för trams.",
    goals: "0",
    assists: "1",
    yellow_cards: "0",
    red_cards: "3",
    mvps: "0",
  },
  {
    name: "Linus Söderberg",
    image: "/Linus.jpg",
    position: "Försvarare",
    description: "Från fjärran land (Vargön)",
    goals: "1",
    assists: "1",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "1",
  },
  {
    name: "Mattias Svaner",
    image: "/Mattias_svanér.jpg",
    position: "Mittfältare",
    description:
      "Lagets lokomotiv, Kanske den ända i laget med en kapacitet att springa mer än 3km oavbrutet.",
    goals: "1",
    assists: "1",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Rasmus Gustavsson",
    image: "/Rasmus_Gustavsson.jpg",
    position: "Målvakt",
    description: "Förstamålvakt samt matchskribent",
    goals: "0",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Rasmus Tell",
    image: "/Rasmus_tell.jpg",
    position: "Mittfältare",
    description: "Är ofta på semester...",
    goals: "0",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Gustaf Rådström",
    image: "/Gustaf_rådström.jpg",
    position: "Försvarare",
    description:
      "2026 Första tillägg, En grabb som ska leda målstatistiken för 2026!",
    goals: "1",
    assists: "0",
    yellow_cards: "1",
    red_cards: "0",
    mvps: "1",
  },
  {
    name: "Alexander Bergström",
    image: PLACEHOLDER_IMAGE,
    position: "Anfallare",
    description: "",
    goals: "1",
    assists: "3",
    yellow_cards: "1",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Paulo ivarsson",
    image: "/paulo.jpg",
    position: "Mittfältare",
    description: "",
    goals: "1",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Mike singh",
    image: PLACEHOLDER_IMAGE,
    position: "Anfallare",
    description: "",
    goals: "7",
    assists: "5",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Elias Myrström",
    image: "/Elias_myrström.jpg",
    position: "Anfallare",
    description: "",
    goals: "3",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
];
