import { Player } from "./player-model";

export const PLACEHOLDER_IMAGE = "/Bollteori-transparent.png";

export function playerSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[åä]/g, "a")
    .replace(/ö/g, "o")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getPlayerBySlug(slug: string): Player | undefined {
  return players.find((p) => playerSlug(p.name) === slug);
}

export const players: Player[] = [
  {
    name: "Andreas Svanström",
    image: "/Adde.jpg",
    position: "Försvarare",
    description:
      "Den här killen ville vinna troféer så då anslöt han sig till Bollteori för att ta hem den största troféen av alla, Korpen Trofén",
    goals: "18",
    assists: "22",
    yellow_cards: "0",
    red_cards: "0",
    amountofGlidTackles: "4",
    matches_played: "20",
    mvps: "2",
  },
  {
    name: "Oscar Ponce Johansson",
    image: "/Oscar_ponce.jpg",
    position: "Mittfältare",
    description: "Herr Krabba",
    goals: "5",
    assists: "1",
    yellow_cards: "1",
    red_cards: "0",
    matches_played: "52",
    mvps: "0",
  },
  {
    name: "Robin Jakobsson",
    image: "/Robin_jakobsson.jpg",
    position: "Försvarare",
    description:
      "En Stenhård back som gjorde sin bästa match i livet när han var målvakt. Åkt på stryk av Paulo.",
    goals: "2",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    amountofGlidTackles: "5",
    matches_played: "60",
    mvps: "0",
  },
  {
    name: "Filip Rolf-Olsson",
    image: "/Rolf.jpg",
    position: "Mittfältare",
    description: "Mer känd som Mr. Monke… ~150 cm",
    goals: "5",
    assists: "2",
    yellow_cards: "0",
    red_cards: "0",
    matches_played: "21",
    mvps: "1",
  },
  {
    name: "Tom Alexandersson",
    image: "/Tom.jpg.jpg",
    position: "Försvarare",
    description:
      'Definitionen av en "föredetting" Numera en kona i backlinjen...',
    goals: "0",
    assists: "0",
    yellow_cards: "0",
    matches_played: "23",
    amountofGlidTackles: "3",
    red_cards: "0",
    mvps: "5",
  },
  {
    name: "Erik Olsson Lidman",
    image: "/Erik_lidman.jpg",
    position: "Försvarare",
    description:
      "Snabba brillor och trädgårdshandskar i 20 grader plus är Erkans signatur.",
    goals: "3",
    assists: "2",
    yellow_cards: "0",
    matches_played: "26",
    red_cards: "0",
    mvps: "0",
  },
  {
    name: "Jesper Berntsson",
    image: "/Jeppe.jpg",
    position: "Målvakt",
    description: "Fjärdemålis och maskot med ansvar för trams.",
    goals: "0",
    assists: "1",
    yellow_cards: "0",
    matches_played: "21",
    red_cards: "3",
    mvps: "0",
  },
  {
    name: "Linus Söderberg",
    image: "/Linus.jpg",
    position: "Försvarare",
    description: "Från fjärran land (Vargön)",
    goals: "1",
    assists: "2",
    yellow_cards: "0",
    matches_played: "31",
    red_cards: "0",
    mvps: "1",
  },
  {
    name: "Mattias Svaner",
    image: "/Mattias_svanér.jpg",
    position: "Mittfältare",
    description:
      "Lagets lokomotiv, Kanske den ända i laget med en kapacitet att springa mer än 3km oavbrutet.",
    goals: "2",
    assists: "1",
    yellow_cards: "0",
    red_cards: "0",
    amountofGlidTackles: "1",
    mvps: "0",
    matches_played: "26",
  },
  {
    name: "Rasmus Gustavsson",
    image: "/Rasmus_Gustavsson.jpg",
    position: "Målvakt",
    description: "Förstamålvakt samt matchskribent",
    goals: "0",
    assists: "0",
    yellow_cards: "0",
    holding_thenulls: "5",
    amountofSaves: "77",
    red_cards: "0",
    mvps: "1",
    matches_played: "26",
  },
  {
    name: "Rasmus Tell",
    image: "/Rasmus_tell.jpg",
    position: "Mittfältare",
    description: "Är ofta på semester...",
    goals: "2",
    assists: "2",
    yellow_cards: "0",
    red_cards: "0",
    matches_played: "44",
    mvps: "0",
  },
  {
    name: "Gustaf Rådström",
    image: "/Gustaf_rådström.jpg",
    position: "Försvarare",
    description:
      "2026 Första tillägg, En grabb som ska leda målstatistiken för 2026!",
    goals: "2",
    assists: "0",
    yellow_cards: "1",
    red_cards: "0",
    matches_played: "9",
    mvps: "1",
  },
  {
    name: "Alexander Bergström",
    image: PLACEHOLDER_IMAGE,
    position: "Anfallare",
    description: "",
    goals: "5",
    assists: "3",
    yellow_cards: "1",
    red_cards: "0",
    mvps: "0",
    matches_played: "26",
  },
  {
    name: "Paulo ivarsson",
    image: "/paulo.jpg",
    position: "Mittfältare",
    description: "",
    goals: "4",
    assists: "0",
    yellow_cards: "0",
    red_cards: "0",
    matches_played: "31",
    mvps: "0",
  },
  {
    name: "Mike singh",
    image: PLACEHOLDER_IMAGE,
    position: "Anfallare",
    description: "",
    goals: "12",
    assists: "9",
    yellow_cards: "0",
    red_cards: "0",
    matches_played: "10",
    mvps: "0",
  },
  {
    name: "Elias Myrström",
    image: "/Elias_myrström.jpg",
    position: "Anfallare",
    description: "",
    goals: "4",
    assists: "1",
    amountofGlidTackles: "1",
    matches_played: "34",
    yellow_cards: "0",
    red_cards: "0",
    mvps: "0",
  },
];
